### ISSUE TITLE
can't print a png file well display on Windows

### ISSUE THREAD

**Issue by sangshuduo** [darrenburns/rich-pixels#12]
Hello,

I tried to use rich-pixels to print a png file on the Powershell console of Windows 11 but I got a white screen only. I can use a Rust utility viu to print it well.
`
from rich_pixels import Pixels
from rich.console import Console

console = Console()
pixels = Pixels.from_image_path("file.png")
console.print(pixels)
`

![file](https://github.com/darrenburns/rich-pixels/assets/825729/caabd23e-38a3-44fd-af4d-95b97418ec93)

**Comment by macieka** [comment]
Its probably there, but very big. Try to add ```resize``` argument to ```from_image_path``` method.

**Comment by sangshuduo** [comment]
> Its probably there, but very big. Try to add `resize` argument to `from_image_path` method.

You are right. It does show up after I use `from_image_path("file.png", (80, 50))` .  The resolution looks a little coarser than what the `viu` does. Is there any plan to improve?

**Comment by darrenburns** [comment]
We now use half block characters, so it should hopefully match `viu` in terms of resolution. There's no plan to support iTerm/Kitty image protocols like viu does though.
