### ISSUE TITLE
Feature Request: Image format function

### ISSUE THREAD

**Issue by jbae-89** [darrenburns/rich-pixels#13]
I would like to see a rich-pixel version of the standard library .format() which would allow users to do something like this:
There may additionally need to be a function that tells rich-pixels what color is going to be used for string replacement

i.e) 
```
my_image = example.png
image.set_format('pink')
render.image(my_image).format(ip_address01, ip_address02)
```

![rich_pixel_image](https://github.com/darrenburns/rich-pixels/assets/66644010/323e30e9-f7a2-4530-a332-1c5e25c4a690)

Which would take this image and fill in two IP addresses with the format of 000.000.000.000

**Comment by darrenburns** [comment]
This is outwith the scope of what I want to offer with this library, sorry!
