### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by murilo-cunha** [darrenburns/rich-pixels#2]
Hi, really like your package!

Was wondering if you'd be interested in extending support to 3.7?

I'd like to use `rich-pixels` for another project but I start support at 3.7, and I see that you start supporting at 3.8.

At a first glance, I think the main changes would be typing hints? And I could gladly take this up as well 🙃

**Comment by darrenburns** [comment]
Hi, thanks! I'd accept a PR for this. I think it's just the type hints and updating the pyproject file, yes 🙂
