### ISSUE TITLE
Tests not passing

### ISSUE THREAD

**Issue by erdurano** [darrenburns/rich-pixels#4]
Hey, first of all great implementation. Due to the lack of data "sample_files" directory, tests are failing. Could you provide the files? Hoping to extend the implementation and need the image files to ensure there is no breakage

**Comment by darrenburns** [comment]
Hey, yes, I just noticed these weren't checked in this morning. I'll add them to the repo later tonight :)

**Comment by erdurano** [comment]
Thanks for your response 😊 Excuse my enthusiasm since I basically just yesterday managed to finish creation of an algorithm for Unicode/ascii renderer. Also, if you are willing, I have an idea to create several image renderer types to be usable like Pixels or within it. Should i mature the idea in a fork of your project or would you want to discuss beforehand?

**Comment by darrenburns** [comment]
Yes, I'd be open to having multiple algorithms! Would be nice to see an example of the output, and need some discussion on what the user-facing API would look like, but I like the idea :)

**Comment by erdurano** [comment]
Please check your twitter DM in your convenience. I din't want to create unrelated discussion here, so sent a message there.😁

**Comment by darrenburns** [comment]
Fixed the issue with the tests now - forgot I originally had that file in the `.gitignore` before referring to it in the tests, so it didn't get checked in. Will set up CI soon.
