### ISSUE TITLE
Draft of subpixel / single-space rasterization

### ISSUE THREAD

**Issue by torshepherd** [darrenburns/rich-pixels#8]
![image](https://user-images.githubusercontent.com/49597791/210481550-58e9f474-8ca8-400b-8ce6-2874317c8153.png)

I've got a quick and dirty rasterization of half-blocks and single-spaces. I can open a PR later this week if this is of interest :)

**Comment by labo-China** [comment]
Hello! I\`m currently working on an application that requires displaying a picture in terminal and I`m interested in your solution.
May I see your code? Or at least get some informations about how to implement it?
Thanks for your further help!

**Comment by JuerGenie** [comment]
> Hello! I`m currently working on an application that requires displaying a picture in terminal and I`m interested in your solution. May I see your code? Or at least get some informations about how to implement it? Thanks for your further help!

I don't know if you still need help, but I hope this pr(#16)  can help you 😊.

**Comment by labo-China** [comment]
Thanks for your help! That is what exactly I am looking for!
Hope your PR get merged soon!

**Comment by darrenburns** [comment]
Closing as the half cell support PR is now merged and available in 3.0.1.
